# Generated by Django 3.0.7 on 2020-06-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200618_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdoctor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
