# Generated by Django 3.0.7 on 2020-06-18 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='myfile')),
                ('causes', models.TextField(blank=True)),
                ('stages', models.TextField(blank=True)),
                ('image2', models.ImageField(default='default.jpg', upload_to='myfile2')),
                ('consequences', models.TextField(blank=True)),
                ('remedies_and_treatment', models.TextField(blank=True)),
                ('image3', models.ImageField(default='default.jpg', upload_to='myfile3')),
                ('question_and_answer', models.TextField(blank=True)),
                ('prevention', models.TextField(blank=True)),
                ('adverse', models.TextField(blank=True)),
                ('side_effect', models.TextField(blank=True)),
                ('diagnosis', models.CharField(max_length=100)),
                ('symptomps', models.CharField(max_length=100)),
                ('doc_user_id', models.CharField(max_length=100)),
                ('ref_link', models.TextField(blank=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.RegDoctor')),
            ],
        ),
    ]
